### ISSUE TITLE
Copy link and enter word will result error

### ISSUE THREAD

**Issue by pftom** [tuture-dev/editure#13]
![2020-03-27 11-38-38 2020-03-27 11_39_45](https://user-images.githubusercontent.com/26423749/77719239-c46d0e80-701f-11ea-93a4-f8514ac20e25.gif)

**Comment by mrcfps** [comment]
@pftom This issue seems resolved. Please re-check it.

**Comment by pftom** [comment]
@mRcfps Yup, I'll close it
