### ISSUE TITLE
Insert image in  note with empty content will result error

### ISSUE THREAD

**Issue by pftom** [tuture-dev/editure#21]
![2020-04-09 11-45-29 2020-04-09 11_46_31](https://user-images.githubusercontent.com/26423749/78856132-72cd7680-7a58-11ea-983d-33cdb2ba7f3d.gif)

**Comment by pftom** [comment]
Blockquote also result error

**Comment by pftom** [comment]
Issue two

![2020-04-09 12-09-29 2020-04-09 12_10_57](https://user-images.githubusercontent.com/26423749/78857157-35b6b380-7a5b-11ea-9dcc-fa9dd6b1739a.gif)

**Comment by mrcfps** [comment]
Closed via #22.
