### ISSUE TITLE
Copy content in codeblock will break line

### ISSUE THREAD

**Issue by pftom** [tuture-dev/editure#5]
**Describe the bug**
Copy content in codeblock will break line

**To Reproduce**
1. Go to 'codeblock'
2. Copy some content and then will break line

**Expected behavior**
not break line

**Screenshots**
![image](https://user-images.githubusercontent.com/26423749/76816489-57958f80-683b-11ea-80a3-c14febc4691b.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version  80.0.3987.132

**Additional context**

**Comment by pftom** [comment]
Issue 2：In codeblock, copy and paste content will lost lineBreak

![image](https://user-images.githubusercontent.com/26423749/76817644-6af62a00-683e-11ea-8cbb-107d29776409.png)

**Comment by mrcfps** [comment]
@pftom This issue seems resolved. Please re-check it.
