### ISSUE TITLE
Select all in codeblock and delete will show errors

### ISSUE THREAD

**Issue by pftom** [tuture-dev/editure#8]
![2020-03-21 11-01-04 2020-03-21 11_01_26](https://user-images.githubusercontent.com/26423749/77218189-99884380-6b63-11ea-8ba7-d7d5baa3ea20.gif)

**Comment by mrcfps** [comment]
@pftom Hi, this issue is now perfectly resolved in `0.1.x` version:

![Mar-21-2020 15-06-30](https://user-images.githubusercontent.com/23410977/77221557-9f8f1c00-6b85-11ea-9696-0b0cd8d01b3e.gif)

The editure used in tuture has not been updated to latest. Wait for my PR!

**Comment by pftom** [comment]
@mRcfps Great news, I'm looking forward it
